{{- if .Values.agentchat.configYamlContent }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentchat.fullname" $ }}-config
data:
  agentchat.yaml: |
{{ .Values.agentchat.configYamlContent | toYaml | indent 4 }}

{{- end }}